#!/bin/sh

eval $(env | grep "^SYNOPKG_PKGHOME=")
eval $(env | grep "^config_script=")
eval $(env | grep "^known_scripts_path=")
eval $(env | grep "^config_search=")
eval $(env | grep "^config_wait=")
eval $(env | grep "^config_beep=")
eval $(env | grep "^config_led=")
eval $(env | grep "^config_notify=")

echo "SCRIPT=$config_script" > "$SYNOPKG_PKGHOME/config"
echo "KNOWNSCRIPTSFILEPATH=\"$known_scripts_path\"" >> "$SYNOPKG_PKGHOME/config"
echo "TRIES=$config_search" >> "$SYNOPKG_PKGHOME/config"
echo "WAIT=$config_wait" >> "$SYNOPKG_PKGHOME/config"
if [ $config_beep = "true" ]
then
	echo "BEEP=1" >> "$SYNOPKG_PKGHOME/config"
else
	echo "BEEP=0" >> "$SYNOPKG_PKGHOME/config"
fi
if [ $config_led = "true" ]
then
	echo "LED=1" >> "$SYNOPKG_PKGHOME/config"
else
	echo "LED=0" >> "$SYNOPKG_PKGHOME/config"
fi
if [ -z "$config_notify" ]
then
	echo "NOTIFY=0" >> "$SYNOPKG_PKGHOME/config"
else
	echo "NOTIFY=1" >> "$SYNOPKG_PKGHOME/config"
fi
echo "NOTIFYTARGET=$config_notify" >> "$SYNOPKG_PKGHOME/config"

echo "`date +%Y-%m-%d` `date +%H:%M:%S`: autorun installed<br/>" >> "$SYNOPKG_PKGVAR/log"


exit 0
