#!/bin/sh

if [ -d "$SYNOPKG_TEMP_UPGRADE_FOLDER" ]
then
    # restore config
    if [ -f "$SYNOPKG_TEMP_UPGRADE_FOLDER/config" ]
    then
        cp $SYNOPKG_TEMP_UPGRADE_FOLDER/config $SYNOPKG_PKGHOME/
    fi

    # restore log
    if [ -f "$SYNOPKG_TEMP_UPGRADE_FOLDER/log" ]
    then
        cp $SYNOPKG_TEMP_UPGRADE_FOLDER/log $SYNOPKG_PKGVAR/
    fi

    echo "`date +%Y-%m-%d` `date +%H:%M:%S`: autorun upgraded<br/>" >> "$SYNOPKG_PKGVAR/log"
fi

# clean-up
#rm -r /tmp/net.reidemeister.autorun

exit 0
