#!/bin/sh

#DSMMAJOR=`/bin/get_key_value /etc.defaults/VERSION majorversion`
if [ $SYNOPKG_DSM_VERSION_MAJOR -lt 7 ]; then
	echo "This package can only be used in DSM 7.0 and above!" > $SYNOPKG_TEMP_LOGFILE
	exit 1
fi

exit 0
