#!/bin/sh

#clean-up temp when required
#if [ -d "/tmp/net.reidemeister.autorun" ]
#then
#    rm -r /tmp/net.reidemeister.autorun
#fi

# create temp
#mkdir /tmp/net.reidemeister.autorun

# save config
cp $SYNOPKG_PKGHOME/config $SYNOPKG_TEMP_UPGRADE_FOLDER

# save log
cp $SYNOPKG_PKGVAR/log $SYNOPKG_TEMP_UPGRADE_FOLDER

exit 0
